### ISSUE TITLE
The committer has not been found in the system

### ISSUE THREAD

**Issue by austinmw** [ljnsn/cz-conventional-gitmoji#197]
Hi, I get the following pre-commit error:

![image](https://github.com/user-attachments/assets/8a61ac48-2038-4816-ad93-acabf7179e12)

pre-commit config:
```
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.0
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [push]

  - repo: https://github.com/ljnsn/cz-conventional-gitmoji
    rev: v0.3.3
    hooks:
      - id: conventional-gitmoji
```

pyproject.toml:

```
[tool.commitizen]
name = "cz_gitmoji"
```

run command:
`poetry run cz c`

**Comment by ljnsn** [comment]
Change your commitizen hook to look like this:

```
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.0
    hooks:
      - id: commitizen
        additional_dependencies: [cz-conventional-gitmoji]
      - id: commitizen-branch
        stages: [push]
```

Thanks for the report, should mention that in the readme.
