### ISSUE TITLE
How to automatically add emoji?

### ISSUE THREAD

**Issue by luren-dc** [ljnsn/cz-conventional-gitmoji#249]
I saw this in the document, but there is no relevant help to tell me how to do it.

> Add hook to automatically prepend the appropriate gitmoji for the commit's type.

**Comment by ljnsn** [comment]
Hi, the readme mentions that to automatically add the gitmoji, you need to set up the pre-commit hook for the `gitmojify` command like so:

```yaml
repos:
  - repo: https://github.com/ljnsn/cz-conventional-gitmoji
    rev: 0.2.4
    hooks:
      - id: conventional-gitmoji
```

with the version adjusted to the latest version. Do have a suggestion for how I can make it clear that's the relevant section?
