### ISSUE TITLE
gitmojify not workin either from cli or a commit message

### ISSUE THREAD

**Issue by niksfirefly** [ljnsn/cz-conventional-gitmoji#255]
gitmojify not workin either from cli or a commit message
but 
- works with cz commit
- works bump_message if I set in .cz.toml

my config files:

.pre-commit-config.yaml
```
repos:
  - repo: https://github.com/ljnsn/cz-conventional-gitmoji
    rev: v0.7.0
    hooks:
      - id: conventional-gitmoji
```

.cz.toml
```
[tool.commitizen]
name = "cz_gitmoji"
version = "3.0.1"
update_changelog_on_bump = true
bump_message = "🔖 bump(release): v$current_version → v$new_version"
```
